Grace m
Marra2342/Hello-World pull request #1
Opened 2022-05-24 21:46 UTC by Marra2342

created Hello Microverse page

2022-05-24 23:40 UTC, omarsalem7 requested changes
Hi @Marra2342 , 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors ✔️
- Descriptive commit messages ✔️

## Required Changes ♻️

- [ ] [Required] Kindly your Pull Request should have a descriptive title telling you what changes are inside.
- [ ] [Required] please make sure that Pull Request should have a summary describing introduced changes in more detail.
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-24 23:40 UTC, omarsalem7 commented on README.md
> +Linters
- [ ] Consider your README file should be descriptive, you can use this [README template](https://github.com/microverseinc/readme-template/blob/master/README.md) and just it for your repo because  README is a text file that introduces and explains a project. It contains information that is commonly required to understand what the project is about.

2022-05-24 23:40 UTC, omarsalem7 commented on .gitignore
> +MIT.Md
- [ ] Please, remove `MIT.Md` from `.gitignore`, it should contains `test.Md`

2022-05-25 00:44 UTC, Marra2342 commented
Added Hello Microverse to my page

2022-05-25 01:19 UTC, Marra2342 commented on .gitignore
> +MIT.Md
Thank you, I will

2022-05-25 01:46 UTC, Marra2342 reviewed
I removed  MIT.Md from .gitignore in the project of Hello Microverse.

2022-05-25 02:12 UTC, merged